guard 'uglify',
  :input => "app/assets/javascripts",
  :output => "public/javascripts",
  :uglifier => {
      :mangle => {
        :toplevel => true
      },
      :compress => {
        :drop_console => true,
      }
    }